### ISSUE TITLE
Implement design + new chart for admin allocation page

### ISSUE THREAD

**Issue by NitayRabi** [Midburn/communities#44]
1.https://app.zeplin.io/project/5c31adc4f5e7fcb018fbeef0/screen/5c4995d387c26e79e41b4b73

**Comment by Michal-Leizerowitz** [comment]
Updated: https://zpl.io/2EPG5mg

**Comment by Michal-Leizerowitz** [comment]
In the buttons, the icons are too close to the text
Design:
![image](https://user-images.githubusercontent.com/38831553/52338133-33e60000-2a12-11e9-991c-6f2cd20198f4.png)

Real life:
![image](https://user-images.githubusercontent.com/38831553/52338106-1fa20300-2a12-11e9-9030-4de472f92b59.png)

**Comment by NitayRabi** [comment]
Duplicates #73
