### ISSUE TITLE
Staging > Communities > Error undefined when navigating to Manage > Manage Camps

### ISSUE THREAD

**Issue by veredo** [Midburn/communities#68]
Steps to reproduce:

1. Login in as Admin. Event: Midburn2019
2. Go to Manage
3. Click on "Manage camps"
4. Led to URL `https://communities.staging.midburn.org/en/camps/management`
5. The page doesnt load and user there is an error undefined in console

Expected:
Page loads successfully 

<img width="1159" alt="screen shot 2019-02-11 at 11 35 53" src="https://user-images.githubusercontent.com/17548577/52555213-bc3d1a00-2df1-11e9-8fb3-17da3f3d97da.png">

**Comment by NitayRabi** [comment]
Fixed
